# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft Related
forge_version=47.4.0
minecraft_version = 1.20.1
minecraft_sdk = forge

# Mod Version (for Local Builds Only)
semver = 999.999.999

# Curse Publishing Info
curse_project_id = 1037738

# Modrinth Publishing Info
modrinth_project_id = F1gm4RsH

# Dependency CurseForge Project IDs and File IDs (essentially the file id is synonymous with version number and archive classifier)
markdownmanual_project_id = 502485
markdownmanual_file_id = 4873115
architectury_project_id = 419699
architectury_file_id = 5137938

# Dependency Version Info
apache_commons_version = 4.4
jei_version = 15.3.0.4
pr_version = 4.19.0-beta+3
ccl_version = 4.4.0.+
cbm_version = 3.3.0.+
network_lib_version = 1.0.4
luaj_version = 3.0.1
luajava_version = 4.0.2
gdx_jnigen_version = 2.5.2
sedna_version = 1.0.71
sedna_version_commit_ref = 5e705b9

# Debug Options
debug_embeddium = false
embeddium_project_id = 908741
embeddium_file_id = 5521846
debug_embeddium_plus_plus = false
embeddium_plus_plus_project_id = 931925
embeddium_plus_plus_file_id = 5436746
debug_oculus = false
oculus_project_id = 581495
oculus_file_id = 5299671

# Repos
native_networking_repo = North-Western-Development/oc2r-native-networking
senda_repo = North-Western-Development/sedna-mc

# Test Dependency Versions
mockito_version = 4.3.1
jupiter_version = 5.8.2
