# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft Related
modId=oc2r
neo_version=21.1.206
minecraft_version = 1.21.1
minecraft_sdk = neoforge

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod Version (for Local Builds Only)
semver = 999.999.999

# Curse Publishing Info
curse_project_id = 1037738

# Modrinth Publishing Info
modrinth_project_id = F1gm4RsH

# Dependency CurseForge Project IDs and File IDs (essentially the file id is synonymous with version number and archive classifier)
markdownmanual_project_id = 502485
markdownmanual_file_id = 4873115
architectury_project_id = 419699
architectury_file_id = 5786327

# Dependency Version Info
apache_commons_version = 4.4
jei_version = 19.25.1.332
pr_version = 4.22.0-beta+33
ccl_version = 4.6.1.+
cbm_version = 3.5.0.+
network_lib_version = 1.0.4
sedna_version = 1.0.67
sedna_version_commit_ref = d5a069c

# Debug Options
debug_embeddium = false
embeddium_project_id = 908741
embeddium_file_id = 5521846
debug_embeddium_plus_plus = false
embeddium_plus_plus_project_id = 931925
embeddium_plus_plus_file_id = 5436746
debug_oculus = false
oculus_project_id = 581495
oculus_file_id = 5299671

# Repos
native_networking_repo = North-Western-Development/oc2r-native-networking
senda_repo = North-Western-Development/sedna-mc

# Test Dependency Versions
mockito_version = 4.3.1
jupiter_version = 5.8.2
