#file: noinspection UndefinedAction,UndefinedParamsPresent
name: build

on:
  workflow_dispatch:
  push:
    branches: [ 'InternetCardChanges-Test' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: oc2r.jar
          path: build/libs/*-all.jar
